FROM              docker.io/redhat/ubi9
RUN               curl -L -o /etc/yum.repos.d/hashi.repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
RUN               curl -o /etc/yum.repos.d/docker.repo https://download.docker.com/linux/rhel/docker-ce.repo
RUN               dnf install https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm -y
RUN               dnf install libicu make terraform azure-cli docker-ce-cli unzip -y
RUN               curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /bin/kubectl && chmod +x /bin/kubectl
RUN               dnf module disable nodejs -y && dnf module enable nodejs:20 -y && dnf install nodejs npm -y
RUN               dnf install maven -y
# ARGOCD
RUN               curl -sSL -o /bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /bin/argocd
RUN               curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 |  bash
RUN               adduser github
WORKDIR           /home/github
COPY              main.sh .
RUN               chmod +x main.sh
RUN               curl -L -o actions-runner-linux-x64-2.331.0.tar.gz \
                   https://github.com/actions/runner/releases/download/v2.331.0/actions-runner-linux-x64-2.331.0.tar.gz \
                   && tar xzf actions-runner-linux-x64-2.331.0.tar.gz \
                   && rm actions-runner-linux-x64-2.331.0.tar.gz
RUN               chown -R github:github /home/github
USER              github
ENTRYPOINT        ["./main.sh"]
